version: '3.8'
services:
  app:
    container_name: node-api
    build: .
    ports:
      - "4545:4545"
    volumes:
      - .:/app
    depends_on:
      - mongodb
    command: "node app/server.js"
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: